### PR TITLE
support partial override for EasyLoader

### PR DESCRIPTION
**Pull request by Lenqth**
Currently, when inputting override in EasyLoader (Flux), you must input all three of model, vae, and clip at the same time or an error will occur.

However, there seems to be a FLUX.1 model that does not include CLIP (e.g. https://civitai.com/models/656083), and I got an error when I load it.

Therefore, I made it possible to override only a part of it, and to not read the overridden VAE and/or CLIP from the checkpoint.

### CODE REVIEW

**Comment by yolain** [comment]
Thanks for you commit, but this is not good practice.
You should load the clip model separately, not load the model from checkpoint to get the clip model.

**Comment by yolain** [comment]
Look like this example:
image

**Comment by Lenqth** [comment]
Thank you, It works. but I have a problem. The model has VAE and Model. I want to use Baked VAE.

I built the workflow below in modified version in this PR. I think this workflow not load the unet twice.
image

If you want to keep behavior of overrides, I planned to do "Add Parameter for Dual CLIP loader to EasyLoader(Flux)" (Like vae_name) in another PR.

**Comment by yolain** [comment]
I think it might be better to write a separate flux ckpt loader has unet and vae output. Because the original loader is already set, and going to modify the widgets would affect everyone's old workflow.

**Comment by Lenqth** [comment]
> I think it might be better to write a separate flux ckpt loader has unet and vae output. Because the original loader is already set, and going to modify the widgets would affect everyone's old workflow.

I will try to write my own custom node to extract unet and vae from ckpt.
Thank you for the advice.

**Pull request closed without merging**
